apiVersion: v1
kind: Service
metadata:
  name: stans
  namespace: stans
spec:
  # ClusterIP exposes the service internally
  # The Ingress routes external traffic to this service
  type: ClusterIP
  selector:
    app: stans        # routes to all pods with label app=stans
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80